pr:
  branches:
    include:
      - main

variables:
  Codeql.Enabled: true

jobs:
  - job: Extension
    displayName: dotnet and dotnet-isolated NuGet packages, java Maven package
    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: 6.x
          performMultiLevelLookup: true

      - task: Bash@3
        displayName: Install Azure Functions Core Tools
        inputs:
          targetType: 'inline'
          script: 'wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb; sudo dpkg -i packages-microsoft-prod.deb; sudo apt-get update; sudo apt-get install -qq -y azure-functions-core-tools-4'

      - task: Bash@3
        displayName: Download & Make Redis 6
        inputs:
          targetType: 'inline'
          script: 'sudo wget -P /redis https://download.redis.io/releases/redis-6.0.20.tar.gz; cd /redis; sudo tar -xzvf redis-6.0.20.tar.gz; cd redis-6.0.20; sudo make'

      - task: Bash@3
        displayName: Download & Make Redis 6.2
        inputs:
          targetType: 'inline'
          script: 'sudo wget -P /redis https://download.redis.io/releases/redis-6.2.14.tar.gz; cd /redis; sudo tar -xzvf redis-6.2.14.tar.gz; cd redis-6.2.14; sudo make'

      - task: Bash@3
        displayName: Download & Make Redis 7
        inputs:
          targetType: 'inline'
          script: 'sudo wget -P /redis https://download.redis.io/releases/redis-7.0.14.tar.gz; cd /redis; sudo tar -xzvf redis-7.0.14.tar.gz; cd redis-7.0.14; sudo make'

      - task: Bash@3
        displayName: Set local.settings.json secret values to environment variables
        inputs:
          targetType: 'inline'
          script: 'sed -i "s/{{AZURE_CACHE_HOST_NAME}}/$(AZURE_CACHE_HOST_NAME)/g; s/{{AZURE_CLIENT_ID}}/$(AZURE_CLIENT_ID)/g; s/{{AZURE_PRINCIPAL_ID}}/$(AZURE_PRINCIPAL_ID)/g; s/{{AZURE_TENANT_ID}}/$(AZURE_TENANT_ID)/g; s/{{AZURE_CLIENT_SECRET}}/$(AZURE_CLIENT_SECRET)/g" $(Build.SourcesDirectory)/test/dotnet/local.settings.json'

      - task: DotNetCoreCLI@2
        displayName: Test Microsoft.Azure.WebJobs.Extensions.Redis Debug
        inputs:
          command: test
          arguments: $(Build.SourcesDirectory)/test/dotnet/Microsoft.Azure.WebJobs.Extensions.Redis.Tests.csproj --configuration Debug