trigger:
  branches:
    include:
      - main

jobs:
  - job: buildExtension
    displayName: WebJobs extension
    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: 6.x
          performMultiLevelLookup: true

      - script: npm install -g azure-functions-core-tools
        displayName: 'Install Azure Functions Core Tools'

      - task: Bash@3
        displayName: Download and start redis server, enable all keyspace/keyevent notifications
        inputs:
          targetType: 'inline'
          script: 'sudo apt-get install -qq -y redis; sudo service redis-server start; redis-cli config set notify-keyspace-events KEA'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --configuration Release

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          arguments: --configuration Debug

      - task: EsrpCodeSigning@2
        displayName: Sign .dll
        inputs:
          connectedServiceName: 'redis-codesign'
          folderPath: src/bin/Release/netstandard2.0
          pattern: Microsoft.Azure.WebJobs.Extensions.Redis.dll
          signConfigType: inlineSignParams
          inlineOperation: |
            [
              {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolSign",
                "Parameters": {
                  "OpusName": "Microsoft",
                  "OpusInfo": "http://www.microsoft.com",
                  "FileDigest": "/fd \"SHA256\"",
                  "PageHash": "/NPH",
                  "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                "ToolName": "sign",
                "ToolVersion": "1.0"
              },
              {
                "KeyCode": "CP-230012",
                "OperationCode": "SigntoolVerify",
                "Parameters": {},
                "ToolName": "sign",
                "ToolVersion": "1.0"
              }
            ]
      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: pack
          searchPatternPack: src/Microsoft.Azure.WebJobs.Extensions.Redis.csproj
          configurationToPack: Release
          outputDir: $(Build.ArtifactStagingDirectory)
          nobuild: true
          includesymbols: true
          verbosityPack: minimal

      - task: EsrpCodeSigning@2
        displayName: Sign .nupkg
        inputs:
            connectedServiceName: 'redis-codesign'
            folderPath: $(Build.ArtifactStagingDirectory)
            pattern: Microsoft.Azure.WebJobs.Extensions.Redis.*.nupkg
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                  {
                    "KeyCode": "CP-401405",
                    "OperationCode": "NuGetSign",
                    "Parameters": {},
                    "ToolName": "sign",
                    "ToolVersion": "1.0"
                  },
                  {
                    "KeyCode": "CP-401405",
                    "OperationCode": "NuGetVerify",
                    "Parameters": {},
                    "ToolName": "sign",
                    "ToolVersion": "1.0"
                  }
              ]

      - task: DeleteFiles@1
        displayName: Cleanup Directory
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)
          contents: CodeSignSummary*.md

      - task: PublishBuildArtifacts@1
        displayName: Publish
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
